import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: `SuarakuNFC | Auth`,
  description: "Generated by create next app",
};

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="flex items-center flex-col justify-center h-screen">
      <Image
        src="/next.svg"
        alt="Logo"
        width={100}
        height={100}
      />

      {children}
    </div>
  );
};

export default AuthLayout;
