import { Metadata } from "next";

export const metadata: Metadata = {
  title: `SuarakuNFC | Auth`,
  description: "Generated by create next app",
};

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="flex items-center flex-col justify-center h-screen gap-[52px] container">
      {children}
    </div>
  );
};

export default AuthLayout;
